/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DoctorRouteRouteImport } from './routes/doctor/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DoctorIndexRouteImport } from './routes/doctor/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SpecialtiesSlugRouteImport } from './routes/specialties/$slug'
import { Route as DoctorSettingsRouteImport } from './routes/doctor/settings'
import { Route as DoctorScheduleRouteImport } from './routes/doctor/schedule'
import { Route as DoctorReportsRouteImport } from './routes/doctor/reports'
import { Route as DoctorProfileRouteImport } from './routes/doctor/profile'
import { Route as DoctorPatientsRouteImport } from './routes/doctor/patients'
import { Route as DoctorNotificationsRouteImport } from './routes/doctor/notifications'
import { Route as DoctorAppointmentsRouteImport } from './routes/doctor/appointments'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminPatientsRouteImport } from './routes/admin/patients'
import { Route as AdminNotificationsRouteImport } from './routes/admin/notifications'
import { Route as AdminDoctorsRouteImport } from './routes/admin/doctors'
import { Route as AdminDepartmentsRouteImport } from './routes/admin/departments'
import { Route as AdminBillingRouteImport } from './routes/admin/billing'
import { Route as AdminAppointmentsRouteImport } from './routes/admin/appointments'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRouteRoute = DoctorRouteRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorIndexRoute = DoctorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DoctorRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const SpecialtiesSlugRoute = SpecialtiesSlugRouteImport.update({
  id: '/specialties/$slug',
  path: '/specialties/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorSettingsRoute = DoctorSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DoctorRouteRoute,
} as any)
const DoctorScheduleRoute = DoctorScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => DoctorRouteRoute,
} as any)
const DoctorReportsRoute = DoctorReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DoctorRouteRoute,
} as any)
const DoctorProfileRoute = DoctorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DoctorRouteRoute,
} as any)
const DoctorPatientsRoute = DoctorPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => DoctorRouteRoute,
} as any)
const DoctorNotificationsRoute = DoctorNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DoctorRouteRoute,
} as any)
const DoctorAppointmentsRoute = DoctorAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => DoctorRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPatientsRoute = AdminPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDoctorsRoute = AdminDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDepartmentsRoute = AdminDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAppointmentsRoute = AdminAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/doctor': typeof DoctorRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/notifications': typeof DoctorNotificationsRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/doctor/reports': typeof DoctorReportsRoute
  '/doctor/schedule': typeof DoctorScheduleRoute
  '/doctor/settings': typeof DoctorSettingsRoute
  '/specialties/$slug': typeof SpecialtiesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/doctor/': typeof DoctorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/notifications': typeof DoctorNotificationsRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/doctor/reports': typeof DoctorReportsRoute
  '/doctor/schedule': typeof DoctorScheduleRoute
  '/doctor/settings': typeof DoctorSettingsRoute
  '/specialties/$slug': typeof SpecialtiesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/doctor': typeof DoctorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/doctor': typeof DoctorRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/notifications': typeof DoctorNotificationsRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/doctor/reports': typeof DoctorReportsRoute
  '/doctor/schedule': typeof DoctorScheduleRoute
  '/doctor/settings': typeof DoctorSettingsRoute
  '/specialties/$slug': typeof SpecialtiesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/doctor/': typeof DoctorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/doctor'
    | '/login'
    | '/admin/appointments'
    | '/admin/billing'
    | '/admin/departments'
    | '/admin/doctors'
    | '/admin/notifications'
    | '/admin/patients'
    | '/admin/reports'
    | '/admin/settings'
    | '/doctor/appointments'
    | '/doctor/notifications'
    | '/doctor/patients'
    | '/doctor/profile'
    | '/doctor/reports'
    | '/doctor/schedule'
    | '/doctor/settings'
    | '/specialties/$slug'
    | '/admin/'
    | '/doctor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/appointments'
    | '/admin/billing'
    | '/admin/departments'
    | '/admin/doctors'
    | '/admin/notifications'
    | '/admin/patients'
    | '/admin/reports'
    | '/admin/settings'
    | '/doctor/appointments'
    | '/doctor/notifications'
    | '/doctor/patients'
    | '/doctor/profile'
    | '/doctor/reports'
    | '/doctor/schedule'
    | '/doctor/settings'
    | '/specialties/$slug'
    | '/admin'
    | '/doctor'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/doctor'
    | '/login'
    | '/admin/appointments'
    | '/admin/billing'
    | '/admin/departments'
    | '/admin/doctors'
    | '/admin/notifications'
    | '/admin/patients'
    | '/admin/reports'
    | '/admin/settings'
    | '/doctor/appointments'
    | '/doctor/notifications'
    | '/doctor/patients'
    | '/doctor/profile'
    | '/doctor/reports'
    | '/doctor/schedule'
    | '/doctor/settings'
    | '/specialties/$slug'
    | '/admin/'
    | '/doctor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  DoctorRouteRoute: typeof DoctorRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SpecialtiesSlugRoute: typeof SpecialtiesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/': {
      id: '/doctor/'
      path: '/'
      fullPath: '/doctor/'
      preLoaderRoute: typeof DoctorIndexRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/specialties/$slug': {
      id: '/specialties/$slug'
      path: '/specialties/$slug'
      fullPath: '/specialties/$slug'
      preLoaderRoute: typeof SpecialtiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/settings': {
      id: '/doctor/settings'
      path: '/settings'
      fullPath: '/doctor/settings'
      preLoaderRoute: typeof DoctorSettingsRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
    '/doctor/schedule': {
      id: '/doctor/schedule'
      path: '/schedule'
      fullPath: '/doctor/schedule'
      preLoaderRoute: typeof DoctorScheduleRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
    '/doctor/reports': {
      id: '/doctor/reports'
      path: '/reports'
      fullPath: '/doctor/reports'
      preLoaderRoute: typeof DoctorReportsRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
    '/doctor/profile': {
      id: '/doctor/profile'
      path: '/profile'
      fullPath: '/doctor/profile'
      preLoaderRoute: typeof DoctorProfileRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
    '/doctor/patients': {
      id: '/doctor/patients'
      path: '/patients'
      fullPath: '/doctor/patients'
      preLoaderRoute: typeof DoctorPatientsRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
    '/doctor/notifications': {
      id: '/doctor/notifications'
      path: '/notifications'
      fullPath: '/doctor/notifications'
      preLoaderRoute: typeof DoctorNotificationsRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
    '/doctor/appointments': {
      id: '/doctor/appointments'
      path: '/appointments'
      fullPath: '/doctor/appointments'
      preLoaderRoute: typeof DoctorAppointmentsRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/patients': {
      id: '/admin/patients'
      path: '/patients'
      fullPath: '/admin/patients'
      preLoaderRoute: typeof AdminPatientsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/doctors': {
      id: '/admin/doctors'
      path: '/doctors'
      fullPath: '/admin/doctors'
      preLoaderRoute: typeof AdminDoctorsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/departments': {
      id: '/admin/departments'
      path: '/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AdminDepartmentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/appointments': {
      id: '/admin/appointments'
      path: '/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AdminAppointmentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAppointmentsRoute: typeof AdminAppointmentsRoute
  AdminBillingRoute: typeof AdminBillingRoute
  AdminDepartmentsRoute: typeof AdminDepartmentsRoute
  AdminDoctorsRoute: typeof AdminDoctorsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPatientsRoute: typeof AdminPatientsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAppointmentsRoute: AdminAppointmentsRoute,
  AdminBillingRoute: AdminBillingRoute,
  AdminDepartmentsRoute: AdminDepartmentsRoute,
  AdminDoctorsRoute: AdminDoctorsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPatientsRoute: AdminPatientsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface DoctorRouteRouteChildren {
  DoctorAppointmentsRoute: typeof DoctorAppointmentsRoute
  DoctorNotificationsRoute: typeof DoctorNotificationsRoute
  DoctorPatientsRoute: typeof DoctorPatientsRoute
  DoctorProfileRoute: typeof DoctorProfileRoute
  DoctorReportsRoute: typeof DoctorReportsRoute
  DoctorScheduleRoute: typeof DoctorScheduleRoute
  DoctorSettingsRoute: typeof DoctorSettingsRoute
  DoctorIndexRoute: typeof DoctorIndexRoute
}

const DoctorRouteRouteChildren: DoctorRouteRouteChildren = {
  DoctorAppointmentsRoute: DoctorAppointmentsRoute,
  DoctorNotificationsRoute: DoctorNotificationsRoute,
  DoctorPatientsRoute: DoctorPatientsRoute,
  DoctorProfileRoute: DoctorProfileRoute,
  DoctorReportsRoute: DoctorReportsRoute,
  DoctorScheduleRoute: DoctorScheduleRoute,
  DoctorSettingsRoute: DoctorSettingsRoute,
  DoctorIndexRoute: DoctorIndexRoute,
}

const DoctorRouteRouteWithChildren = DoctorRouteRoute._addFileChildren(
  DoctorRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  DoctorRouteRoute: DoctorRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SpecialtiesSlugRoute: SpecialtiesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
