/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DoctorRouteRouteImport } from './routes/doctor/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DoctorIndexRouteImport } from './routes/doctor/index'
import { Route as BlogsIndexRouteImport } from './routes/blogs/index'
import { Route as SpecialtiesSlugRouteImport } from './routes/specialties/$slug'
import { Route as DoctorSettingsRouteImport } from './routes/doctor/settings'
import { Route as DoctorScheduleRouteImport } from './routes/doctor/schedule'
import { Route as DoctorReportsRouteImport } from './routes/doctor/reports'
import { Route as DoctorProfileRouteImport } from './routes/doctor/profile'
import { Route as DoctorPatientsRouteImport } from './routes/doctor/patients'
import { Route as DoctorNotificationsRouteImport } from './routes/doctor/notifications'
import { Route as DoctorBlogsRouteImport } from './routes/doctor/blogs'
import { Route as DoctorBillingRouteImport } from './routes/doctor/billing'
import { Route as DoctorAppointmentsRouteImport } from './routes/doctor/appointments'
import { Route as BlogsBlogIdRouteImport } from './routes/blogs/$blogId'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRouteRoute = DoctorRouteRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorIndexRoute = DoctorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DoctorRouteRoute,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialtiesSlugRoute = SpecialtiesSlugRouteImport.update({
  id: '/specialties/$slug',
  path: '/specialties/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorSettingsRoute = DoctorSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DoctorRouteRoute,
} as any)
const DoctorScheduleRoute = DoctorScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => DoctorRouteRoute,
} as any)
const DoctorReportsRoute = DoctorReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DoctorRouteRoute,
} as any)
const DoctorProfileRoute = DoctorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DoctorRouteRoute,
} as any)
const DoctorPatientsRoute = DoctorPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => DoctorRouteRoute,
} as any)
const DoctorNotificationsRoute = DoctorNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DoctorRouteRoute,
} as any)
const DoctorBlogsRoute = DoctorBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => DoctorRouteRoute,
} as any)
const DoctorBillingRoute = DoctorBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DoctorRouteRoute,
} as any)
const DoctorAppointmentsRoute = DoctorAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => DoctorRouteRoute,
} as any)
const BlogsBlogIdRoute = BlogsBlogIdRouteImport.update({
  id: '/blogs/$blogId',
  path: '/blogs/$blogId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/doctor': typeof DoctorRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/blogs/$blogId': typeof BlogsBlogIdRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/billing': typeof DoctorBillingRoute
  '/doctor/blogs': typeof DoctorBlogsRoute
  '/doctor/notifications': typeof DoctorNotificationsRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/doctor/reports': typeof DoctorReportsRoute
  '/doctor/schedule': typeof DoctorScheduleRoute
  '/doctor/settings': typeof DoctorSettingsRoute
  '/specialties/$slug': typeof SpecialtiesSlugRoute
  '/blogs/': typeof BlogsIndexRoute
  '/doctor/': typeof DoctorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/blogs/$blogId': typeof BlogsBlogIdRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/billing': typeof DoctorBillingRoute
  '/doctor/blogs': typeof DoctorBlogsRoute
  '/doctor/notifications': typeof DoctorNotificationsRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/doctor/reports': typeof DoctorReportsRoute
  '/doctor/schedule': typeof DoctorScheduleRoute
  '/doctor/settings': typeof DoctorSettingsRoute
  '/specialties/$slug': typeof SpecialtiesSlugRoute
  '/blogs': typeof BlogsIndexRoute
  '/doctor': typeof DoctorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/doctor': typeof DoctorRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/blogs/$blogId': typeof BlogsBlogIdRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/billing': typeof DoctorBillingRoute
  '/doctor/blogs': typeof DoctorBlogsRoute
  '/doctor/notifications': typeof DoctorNotificationsRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/doctor/reports': typeof DoctorReportsRoute
  '/doctor/schedule': typeof DoctorScheduleRoute
  '/doctor/settings': typeof DoctorSettingsRoute
  '/specialties/$slug': typeof SpecialtiesSlugRoute
  '/blogs/': typeof BlogsIndexRoute
  '/doctor/': typeof DoctorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/doctor'
    | '/login'
    | '/admin/settings'
    | '/blogs/$blogId'
    | '/doctor/appointments'
    | '/doctor/billing'
    | '/doctor/blogs'
    | '/doctor/notifications'
    | '/doctor/patients'
    | '/doctor/profile'
    | '/doctor/reports'
    | '/doctor/schedule'
    | '/doctor/settings'
    | '/specialties/$slug'
    | '/blogs/'
    | '/doctor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/settings'
    | '/blogs/$blogId'
    | '/doctor/appointments'
    | '/doctor/billing'
    | '/doctor/blogs'
    | '/doctor/notifications'
    | '/doctor/patients'
    | '/doctor/profile'
    | '/doctor/reports'
    | '/doctor/schedule'
    | '/doctor/settings'
    | '/specialties/$slug'
    | '/blogs'
    | '/doctor'
  id:
    | '__root__'
    | '/'
    | '/doctor'
    | '/login'
    | '/admin/settings'
    | '/blogs/$blogId'
    | '/doctor/appointments'
    | '/doctor/billing'
    | '/doctor/blogs'
    | '/doctor/notifications'
    | '/doctor/patients'
    | '/doctor/profile'
    | '/doctor/reports'
    | '/doctor/schedule'
    | '/doctor/settings'
    | '/specialties/$slug'
    | '/blogs/'
    | '/doctor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DoctorRouteRoute: typeof DoctorRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  BlogsBlogIdRoute: typeof BlogsBlogIdRoute
  SpecialtiesSlugRoute: typeof SpecialtiesSlugRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/': {
      id: '/doctor/'
      path: '/'
      fullPath: '/doctor/'
      preLoaderRoute: typeof DoctorIndexRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specialties/$slug': {
      id: '/specialties/$slug'
      path: '/specialties/$slug'
      fullPath: '/specialties/$slug'
      preLoaderRoute: typeof SpecialtiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/settings': {
      id: '/doctor/settings'
      path: '/settings'
      fullPath: '/doctor/settings'
      preLoaderRoute: typeof DoctorSettingsRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
    '/doctor/schedule': {
      id: '/doctor/schedule'
      path: '/schedule'
      fullPath: '/doctor/schedule'
      preLoaderRoute: typeof DoctorScheduleRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
    '/doctor/reports': {
      id: '/doctor/reports'
      path: '/reports'
      fullPath: '/doctor/reports'
      preLoaderRoute: typeof DoctorReportsRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
    '/doctor/profile': {
      id: '/doctor/profile'
      path: '/profile'
      fullPath: '/doctor/profile'
      preLoaderRoute: typeof DoctorProfileRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
    '/doctor/patients': {
      id: '/doctor/patients'
      path: '/patients'
      fullPath: '/doctor/patients'
      preLoaderRoute: typeof DoctorPatientsRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
    '/doctor/notifications': {
      id: '/doctor/notifications'
      path: '/notifications'
      fullPath: '/doctor/notifications'
      preLoaderRoute: typeof DoctorNotificationsRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
    '/doctor/blogs': {
      id: '/doctor/blogs'
      path: '/blogs'
      fullPath: '/doctor/blogs'
      preLoaderRoute: typeof DoctorBlogsRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
    '/doctor/billing': {
      id: '/doctor/billing'
      path: '/billing'
      fullPath: '/doctor/billing'
      preLoaderRoute: typeof DoctorBillingRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
    '/doctor/appointments': {
      id: '/doctor/appointments'
      path: '/appointments'
      fullPath: '/doctor/appointments'
      preLoaderRoute: typeof DoctorAppointmentsRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
    '/blogs/$blogId': {
      id: '/blogs/$blogId'
      path: '/blogs/$blogId'
      fullPath: '/blogs/$blogId'
      preLoaderRoute: typeof BlogsBlogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DoctorRouteRouteChildren {
  DoctorAppointmentsRoute: typeof DoctorAppointmentsRoute
  DoctorBillingRoute: typeof DoctorBillingRoute
  DoctorBlogsRoute: typeof DoctorBlogsRoute
  DoctorNotificationsRoute: typeof DoctorNotificationsRoute
  DoctorPatientsRoute: typeof DoctorPatientsRoute
  DoctorProfileRoute: typeof DoctorProfileRoute
  DoctorReportsRoute: typeof DoctorReportsRoute
  DoctorScheduleRoute: typeof DoctorScheduleRoute
  DoctorSettingsRoute: typeof DoctorSettingsRoute
  DoctorIndexRoute: typeof DoctorIndexRoute
}

const DoctorRouteRouteChildren: DoctorRouteRouteChildren = {
  DoctorAppointmentsRoute: DoctorAppointmentsRoute,
  DoctorBillingRoute: DoctorBillingRoute,
  DoctorBlogsRoute: DoctorBlogsRoute,
  DoctorNotificationsRoute: DoctorNotificationsRoute,
  DoctorPatientsRoute: DoctorPatientsRoute,
  DoctorProfileRoute: DoctorProfileRoute,
  DoctorReportsRoute: DoctorReportsRoute,
  DoctorScheduleRoute: DoctorScheduleRoute,
  DoctorSettingsRoute: DoctorSettingsRoute,
  DoctorIndexRoute: DoctorIndexRoute,
}

const DoctorRouteRouteWithChildren = DoctorRouteRoute._addFileChildren(
  DoctorRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DoctorRouteRoute: DoctorRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  BlogsBlogIdRoute: BlogsBlogIdRoute,
  SpecialtiesSlugRoute: SpecialtiesSlugRoute,
  BlogsIndexRoute: BlogsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
